"""followers

Revision ID: 41137024c7ce
Revises: 1cbab43f16ec
Create Date: 2024-03-17 19:10:05.612600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41137024c7ce'
down_revision = '1cbab43f16ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
